# ⚙️ 하이퍼파라미터 및 설정 관리

data:
  sino_dir: sino_Th
  voxel_dir: voxel_Th
  batch_size: 1
  num_workers: 0
  prefetch_factor: null

model:
# if you want to change depth and noise_threshold parameter value, you can change these model's initial value 
#  depth : 5
#  noise_threshold : 0.0
  c1d: null
  c2d: null
  fusion_out: null
  align_out: null
  decoder_hidden: null
  cheat:
    enabled: null
    train_only: null
    out_ch: 64

bp:
  filter: null         # ramp | shepp-logan | cosine | hamming | hann | None
  output_size: null       # null→use X (detector bins)
  angle_chunk: 0

optim:
  lr: 1.0e-4
  weight_decay: 1.0e-2
  betas: null
  eps: 1.0e-6

train:
  epochs: 10
  val_split: 0.5
  val_copy: null
  seed: 2025
  device: auto            # auto | cuda | cpu
  grad_clip: 1.0
#  debug_mode : false

loss_weights:
  w_mse: 1
  w_ec:  1
  w_ssim: 0.1

save:
  dir: result
